### ISSUE TITLE
Invalid provider for the NgModule 'SDKModule' 

### ISSUE THREAD

**Issue by sprypradeep** [mean-expert-official/loopback-sdk-builder#107] opened 2016-09-02 08:39 UTC
- only instances of Provider and Type are allowed, got: [?undefined?, ...]

This seems to be reported for the first 4 providers 
```
      LoopBackAuth,
      ErrorHandler,
      LoggerService,
      JSONSearchParams,
```
Can it be my application specific ? Or a breaking change related to provider set up.

**Comment by pierrecabriere** [comment] 2016-09-02 08:50
Hi, I sent a pull request about this issue.
It should be fixed

**Comment by jonathan-casarrubias** [comment] 2016-09-02 11:49
Hi @pierrecabriere I'm sorry but I can not accept your pull request because it led to [THIS](https://github.com/mean-expert-official/loopback-sdk-builder/issues/108) type of errors.

That already happened between version 2.0.0 and 2.0.1 that I needed to roll back in version 2.0.2

The SDK Builder completely works as it is with the webpack version if you follow the [WIKI instructions](https://github.com/mean-expert-official/loopback-sdk-builder/wiki/1.2.--Update-Builder).

Regards,
Jon

**Comment by pierrecabriere** [comment] 2016-09-02 12:26
Hi @jonathan-casarrubias , even following the WIKI instructions, I have the log error "only instances of Provider and Type are allowed, got: [?undefined?, ...]"

**Comment by jonathan-casarrubias** [comment] 2016-09-02 13:43
@pierrecabriere when we migrated our projects to RC5 we presented the issue you are presenting now, we needed to update every component that uses the SDK according the documentation.

I did accept the first pull request that kind of solved this issue, but brought many issues regarding the other issue #108 you created, the issue with the prototypes.

I'm pretty sure it does work because there are multiple projects already migrated, but I understand it may be a pain, so what I'm thinking is to create a starter that helps everyone as an example and obviously as a started.

Cheers
Jon

**Comment by jonathan-casarrubias** [comment] 2016-09-02 16:37
OK, while creating the starter I found that what was working with angular-cli@webpack it does not work with the latest version which is the 1.0.0-beta.11-webpack.8.

This is going to turn into a critical issue since it looks like the version 8 does not work with any barrel at all and fixing that then creates the prototype problem which not really explainatory.

I need to find a complete solution for this that does not break other parts of the module.

For now please keep using 1.0.0-beta.11-webpack.2, also I found that Angular RC6 does not work with the current Angular CLI.

So you will need to stick to the following configuraitons:

Angular 2 RC 5
1.0.0-beta.11-webpack.2

Cheers
Jon

**Comment by sprypradeep** [comment] 2016-09-02 20:19
Yes, if I comment out the top four providers in sdk.module (using a custom api.service, which is copy), it goes into prototype errors for Api.ts, is there a problem with bundling sequence ?

**Comment by jonathan-casarrubias** [comment] 2016-09-02 20:28
I'm still not sure what the problem is Im digging it right now, the only thing I know is that everything was easier with SystemJS lol.. Sigh...

Anyway, hope to come up with a complete solution ASAP.

Cheers!!!
Jon

**Comment by jonathan-casarrubias** [comment] 2016-09-03 14:29
I have a good progress here... Everything seems to be working now with the latest Angular-cli version... I was able to fix the LoggerService issue, but the way I fixed does not make any sense at all, I just moved from core to custom.. and after that it correctly worked... why? I'm not sure...

There are the same number of directory levels, is called the same way.. anyway I'm working in the test application to make sure everything works correclty..

I believe I will first push to master before publishing into NPM so you may be able to test before is even published.

Cheers
Jon

**Closed** 2016-09-03 15:37 UTC
Labels: bug, dependency issue, to be published

**Comment by hkashlan** [comment] 2016-10-14 00:03
Hi I am using Ionic 2.1.0 but I am facing same problem
and "@mean-expert/loopback-sdk-builder": "^2.0.9",
is there any advice, how can I detect the problem

**Comment by jonathan-casarrubias** [comment] 2016-10-14 11:51
hi @hkashlan within the app.module, you should import from

`import { SDKModule } from './shared/sdk';`

Sometimes with some modules like webpack you will need to also add the index

`import { SDKModule } from './shared/sdk/index';`

and then import within the module

````js
import { BrowserModule } from '@angular/platform-browser';
import { NgModule, ApplicationRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { AppComponent } from './app.component';
import { SDKModule } from './shared/sdk/index';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    SDKModule.forRoot()
  ],
  providers       : [ ],
  entryComponents : [ AppComponent ],
  bootstrap       : [ AppComponent ]
})

export class AppModule {

}
````


This should work, has been tested for a while... unless Ionic changed something really specific that I'm not aware.

Cheers
Jon

**Comment by hkashlan** [comment] 2016-10-15 03:34
It is working great  👍 

Thank you
